name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", ]
body:
  - type: markdown
    attributes:
      value: |     
        For additional support options visit [particular.net/support](https://particular.net/support)
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug 
      description: A clear and concise description of what the bug is.    
      value: | 
        **Description**
        
        **Expected behavior**
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Detailed instructions on how to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Please list the version of the relevant packages or applications in which the bug exists.
      placeholder: "- NuGet package: [e.g. 1.0.0-alpha0073]
                    - OS: [e.g. Windows 10 build 1803]
                    - .NET Version [e.g. .NET Core 2.1.300]"
    validations:
      required: false  
  - type: textarea
    id: work-arounds
    attributes:
      label: Workarounds
      description: If there are any workarounds, please describe here
    validations:
      required: false  
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If there are any possible solutions, please describe here
    validations:
      required: false  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Add screenshots or additional information."
    validations:
      required: false  
   
    
