blank_issues_enabled: false
contact_links:
  - name:  Ask a question
    url: https://discuss.particular.net/
    about: Reach out to the particular discourse community.
  - name: Get support
    url: https://particular.net/support
    about: Please contact us to discuss your support needs.
