blank_issues_enabled: false
contact_links:
  - name: Particular support
    url: https://particular.net/support
    about: Please contact us to discuss your support needs.
  - name: Particular Community Support
    url: https://discuss.particular.net/
    about: Reach out to the particular discourse community.
  - name: Particular consulting
    url: https://particular.net/consulting
    about: Looking for a quick assessment of your major architectural choices before starting a large development effort.
  - name: Particular onsite tranining
    url: https://particular.net/onsite-training
    about: Please contact us for any onsite training.
