name: Demo
description: File a bug report
title: "[Bug]: "
labels: ["bug", ]
body:
  - type: markdown
    attributes:
      value: |     
        For additional support options visit [particular.net/support](https://particular.net/support)
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug 
      description: A clear and concise description of what the bug is.    
      value: | 
        **Description**
        
        **Expected behavior**
                
        **Versions** - Please list the version of the relevant packages or applications in which the bug exists.        
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Detailed instructions on how to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If there are any possible solutions or workarounds, please describe here
    validations:
      required: false  
 
